steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-node-app', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-node-app']

  # Step 3: Deploy the image to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    env:
      - 'CLOUDSDK_APP_DEPLOY_IMAGE_URL=gcr.io/$PROJECT_ID/my-node-app']

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/my-node-app'
